### ISSUE TITLE
Highlighting template tags

### ISSUE THREAD

**Issue by smth** [timkley/eleventy-plugin-torchlight#1]
If you have Nunjucks / Liquid template tags, such as `{{` in your code block 11ty will treat them as part of the template (and probably omit that bit of code). Wrapping the code block in `{% raw %}` tags prevents this (tested in Nunjucks), but I'm wondering if code blocks being treated as raw would be a better default. I guess then you might want some sort of option in this plugin to facilitate dynamic code.

**Comment by timkley** [comment]
Hi Sam, thanks for opening this issue!

Since this plugin does not use the template but the generated HTML to highlight your code there is nothing this plugin could do about this. You could open an issue with 11ty directly, but I don't think this will be fixed. There might be some people that want to use the templating features within code blocks, so using `{% raw %}`, like you did, seems like the right solution for your issue.

Have a nice day 👋
