### ISSUE TITLE
Cannot find module '@torchlight-api/torchlight-cli/lib/config'

### ISSUE THREAD

**Issue by smth** [timkley/eleventy-plugin-torchlight#2]
My build is failing on Netlify, after [updating the build image](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239). I get `Eleventy:EleventyErrorHandler Cannot find module '@torchlight-api/torchlight-cli/lib/config'`. I don't know where the problem lies, but the build is successful if I remove this plugin.

**Comment by timkley** [comment]
Hi! Do you have a repo for reproduction? I think my site also runs the latest build image without failing.

**Comment by smth** [comment]
I don't at the moment I'm afraid. If it's working for you feel free to close this. If I try readding the plugin I'll report back.

**Comment by timkley** [comment]
I just double-checked, I'm using 20.04 as build image and don't get the error.

Maybe the repo [of my site](https://github.com/timkley/tim-kleyersburg.de) could help you?

**Comment by aaronstezycki** [comment]
Just got the same error from a normal local dev build. Looking inside node modules ... @torchlight-api/torchlight-cli/lib/config, the directory 'lib' does not exist.

**Comment by aaronstezycki** [comment]
'@torchlight-api/torchlight-cli/src/config' does exist.

**Comment by aaronstezycki** [comment]
... but simply changing this just results in more errors.

**Comment by timkley** [comment]
Which Node version are you using for the local installation? Will look into this.

**Comment by timkley** [comment]
@aaronstezycki @smth so I took another look at this. The problem should only appears in never versions of [torchlight-cli](https://github.com/torchlight-api/torchlight-cli) because paths changed.

I already pinned the version of the CLI to stop this from happening, maybe you are using an older version of my plugin? In that case I suggest updating it to the most current version (0.2.0). **Please note:** with the bump to 0.2.0 I've updated 11ty to v1. If this somehow is not compatible with your site you should be able to use 0.1.8 which already pinned the torchlight-cli.

Let me know if this fixes this issue 😊
